/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cecs;

import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Patil
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    String nm1;
    String id1;
    public Bill() {
        initComponents();
    }
    public Bill(String nm,String id) {
        initComponents();
        nm1=nm;
        id1=id;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        origin = new javax.swing.JLabel();
        destination = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        servicetype = new javax.swing.JLabel();
        receiveradress = new javax.swing.JLabel();
        dimensions = new javax.swing.JLabel();
        sendername = new javax.swing.JLabel();
        sendername2 = new javax.swing.JLabel();
        origin1 = new javax.swing.JTextField();
        setid = new javax.swing.JTextField();
        destination1 = new javax.swing.JTextField();
        type1 = new javax.swing.JTextField();
        weight1 = new javax.swing.JTextField();
        dimension1 = new javax.swing.JTextField();
        receivername1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        senderadress1 = new javax.swing.JTextArea();
        as = new javax.swing.JLabel();
        servicetype1 = new javax.swing.JTextField();
        sendername1 = new javax.swing.JTextField();
        aa = new javax.swing.JLabel();
        receiveradress2 = new javax.swing.JLabel();
        receiveradress3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiveradress1 = new javax.swing.JTextArea();
        amount1 = new javax.swing.JTextField();
        receiveradress4 = new javax.swing.JLabel();
        getid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        as1 = new javax.swing.JLabel();
        doo = new javax.swing.JTextField();
        as2 = new javax.swing.JLabel();
        dod = new javax.swing.JTextField();
        sendername3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Order ID");

        origin.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        origin.setForeground(new java.awt.Color(255, 255, 255));
        origin.setText("Origin");

        destination.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        destination.setForeground(new java.awt.Color(255, 255, 255));
        destination.setText("Destination");

        type.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");

        weight.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        weight.setForeground(new java.awt.Color(255, 255, 255));
        weight.setText("Weight");

        servicetype.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        servicetype.setForeground(new java.awt.Color(255, 255, 255));
        servicetype.setText("Service Type");

        receiveradress.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress.setText("Receiver Address");

        dimensions.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        dimensions.setForeground(new java.awt.Color(255, 255, 255));
        dimensions.setText("Dimensions");

        sendername.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sendername.setForeground(new java.awt.Color(255, 255, 255));
        sendername.setText("Cargo Express Courier System");

        sendername2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sendername2.setForeground(new java.awt.Color(255, 255, 255));
        sendername2.setText("Bill");

        setid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setidActionPerformed(evt);
            }
        });

        senderadress1.setColumns(20);
        senderadress1.setRows(5);
        jScrollPane1.setViewportView(senderadress1);

        as.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        as.setForeground(new java.awt.Color(255, 255, 255));
        as.setText("Amount");

        aa.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 255, 255));
        aa.setText("Sender Name");

        receiveradress2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress2.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress2.setText("Sender Address");

        receiveradress3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress3.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress3.setText("Receiver Name");

        receiveradress1.setColumns(20);
        receiveradress1.setRows(5);
        jScrollPane2.setViewportView(receiveradress1);

        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });

        receiveradress4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress4.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress4.setText("Enter Order ID");

        getid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getidActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 102, 0));
        jButton7.setText("Generate Bill");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 102, 0));
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        as1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        as1.setForeground(new java.awt.Color(255, 255, 255));
        as1.setText("Date of Order");

        doo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dooActionPerformed(evt);
            }
        });

        as2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        as2.setForeground(new java.awt.Color(255, 255, 255));
        as2.setText("Date of Delivery");

        dod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodActionPerformed(evt);
            }
        });

        sendername3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sendername3.setForeground(new java.awt.Color(255, 255, 255));
        sendername3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/1000_F_276036749_G1khwlIPyVnd9O07KbPkPyG7eEStcldi (2).png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/mainlogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destination)
                    .addComponent(weight)
                    .addComponent(servicetype)
                    .addComponent(dimensions)
                    .addComponent(type)
                    .addComponent(origin)
                    .addComponent(jLabel8)
                    .addComponent(as)
                    .addComponent(receiveradress4)
                    .addComponent(as1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getid, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setid, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimension1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origin1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicetype1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(as2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(receivername1)
                                .addComponent(jScrollPane1)
                                .addComponent(sendername1)
                                .addComponent(aa)
                                .addComponent(receiveradress2)
                                .addComponent(receiveradress3)
                                .addComponent(receiveradress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendername3)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sendername)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sendername2)
                        .addGap(387, 387, 387))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sendername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendername2)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(receiveradress4)
                                .addComponent(getid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(origin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(destination1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destination))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(type1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimensions, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dimension1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(weight)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(weight1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(servicetype)
                                    .addComponent(servicetype1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(as)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendername1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveradress2)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveradress3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receivername1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveradress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(sendername3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(as1)
                        .addComponent(doo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(as2)
                        .addComponent(dod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setidActionPerformed

    private void getidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getidActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try{
            java.sql.Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/CECS","root","password");
            String sql1="SELECT * FROM ORDERDETAILS WHERE id=?";
            java.sql.PreparedStatement Psmt1=Con.prepareStatement(sql1);
            String i=getid.getText();
            Psmt1.setString(1,i);
            java.sql.ResultSet rs=Psmt1.executeQuery();
            while(rs.next())
            {
                String id=rs.getString("id");
                setid.setText(id);
                setid.setEditable(false);
                String org=rs.getString("origin");
                origin1.setText(org);
                origin1.setEditable(false);
                String des=rs.getString("destination");
                destination1.setText(des);
                destination1.setEditable(false);
                String ty=rs.getString("type");
                type1.setText(ty);
                type1.setEditable(false);
                String wt=rs.getString("weight");
                weight1.setText(wt);
                weight1.setEditable(false);
                String dn=rs.getString("dimension");
                dimension1.setText(dn);
                dimension1.setEditable(false);
                String st=rs.getString("servicetype");
                servicetype1.setText(st);
                servicetype1.setEditable(false);
                String sn=rs.getString("sendername");
                sendername1.setText(sn);
                sendername1.setEditable(false);
                String rn=rs.getString("receivername");
                receivername1.setText(rn);
                receivername1.setEditable(false);
                String sa=rs.getString("senderadress");
                senderadress1.setText(sa);
                senderadress1.setEditable(false);
                String ra=rs.getString("receiveradress");
                receiveradress1.setText(ra); 
                receiveradress1.setEditable(false);
                String amn=rs.getString("amount");
                amount1.setText(amn);  
                amount1.setEditable(false);
                String d=rs.getString("orderdate");
                doo.setText(d);
                doo.setEditable(false);
                String dr=rs.getString("receivedate");
                dod.setText(dr);
                dod.setEditable(false);
            }
            if(setid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please Enter Correct ID");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Details Displayed Plesase Check");
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new CustomerPage(nm1,id1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount1ActionPerformed

    private void dooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dooActionPerformed

    private void dodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JTextField amount1;
    private javax.swing.JLabel as;
    private javax.swing.JLabel as1;
    private javax.swing.JLabel as2;
    private javax.swing.JLabel destination;
    private javax.swing.JTextField destination1;
    private javax.swing.JTextField dimension1;
    private javax.swing.JLabel dimensions;
    private javax.swing.JTextField dod;
    private javax.swing.JTextField doo;
    private javax.swing.JTextField getid;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel origin;
    private javax.swing.JTextField origin1;
    private javax.swing.JLabel receiveradress;
    private javax.swing.JTextArea receiveradress1;
    private javax.swing.JLabel receiveradress2;
    private javax.swing.JLabel receiveradress3;
    private javax.swing.JLabel receiveradress4;
    private javax.swing.JTextField receivername1;
    private javax.swing.JTextArea senderadress1;
    private javax.swing.JLabel sendername;
    private javax.swing.JTextField sendername1;
    private javax.swing.JLabel sendername2;
    private javax.swing.JLabel sendername3;
    private javax.swing.JLabel servicetype;
    private javax.swing.JTextField servicetype1;
    private javax.swing.JTextField setid;
    private javax.swing.JLabel type;
    private javax.swing.JTextField type1;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weight1;
    // End of variables declaration//GEN-END:variables
}
