/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cecs;

import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Patil
 */
public class UpdateStatus extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStatus
     */
    String nm1;
    String id1;
    public UpdateStatus() {
        initComponents();
    }
    public UpdateStatus(String nm,String id) {
        initComponents();
        nm1=nm;
        id1=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        origin = new javax.swing.JLabel();
        destination = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        servicetype = new javax.swing.JLabel();
        receiveradress = new javax.swing.JLabel();
        dimensions = new javax.swing.JLabel();
        origin1 = new javax.swing.JTextField();
        setid = new javax.swing.JTextField();
        destination1 = new javax.swing.JTextField();
        type1 = new javax.swing.JTextField();
        weight1 = new javax.swing.JTextField();
        dimension1 = new javax.swing.JTextField();
        receivername1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        senderadress1 = new javax.swing.JTextArea();
        as = new javax.swing.JLabel();
        servicetype1 = new javax.swing.JTextField();
        sendername1 = new javax.swing.JTextField();
        aa = new javax.swing.JLabel();
        receiveradress2 = new javax.swing.JLabel();
        receiveradress3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        receiveradress1 = new javax.swing.JTextArea();
        amount1 = new javax.swing.JTextField();
        receiveradress4 = new javax.swing.JLabel();
        getid = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        pr = new javax.swing.JLabel();
        progress = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        receiveradress5 = new javax.swing.JLabel();
        pr1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Order ID");

        origin.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        origin.setForeground(new java.awt.Color(255, 255, 255));
        origin.setText("Origin");

        destination.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        destination.setForeground(new java.awt.Color(255, 255, 255));
        destination.setText("Destination");

        type.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Type");

        weight.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        weight.setForeground(new java.awt.Color(255, 255, 255));
        weight.setText("Weight");

        servicetype.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        servicetype.setForeground(new java.awt.Color(255, 255, 255));
        servicetype.setText("Service Type");

        receiveradress.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress.setText("Receiver Address");

        dimensions.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        dimensions.setForeground(new java.awt.Color(255, 255, 255));
        dimensions.setText("Dimensions");

        setid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setidActionPerformed(evt);
            }
        });

        senderadress1.setColumns(20);
        senderadress1.setRows(5);
        jScrollPane1.setViewportView(senderadress1);

        as.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        as.setForeground(new java.awt.Color(255, 255, 255));
        as.setText("Amount");

        aa.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        aa.setForeground(new java.awt.Color(255, 255, 255));
        aa.setText("Sender Name");

        receiveradress2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress2.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress2.setText("Sender Address");

        receiveradress3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress3.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress3.setText("Receiver Name");

        receiveradress1.setColumns(20);
        receiveradress1.setRows(5);
        jScrollPane2.setViewportView(receiveradress1);

        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });

        receiveradress4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        receiveradress4.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress4.setText("Enter Order ID");

        getid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getidActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 102, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/verify.png"))); // NOI18N
        jButton7.setText("Verify");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 102, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/back.jpg"))); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        pr.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        pr.setForeground(new java.awt.Color(255, 255, 255));
        pr.setText("Progress");

        progress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20 (Order Placed)", "40 (Order Shipped)", "60 (In Shipping)", "80 (Arrived at final destination)", "100 (Order Delivered)" }));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 102, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/refresh.png"))); // NOI18N
        jButton9.setText("Update Status");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        receiveradress5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        receiveradress5.setForeground(new java.awt.Color(255, 255, 255));
        receiveradress5.setText("Cargo Express Courier System");

        pr1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        pr1.setForeground(new java.awt.Color(255, 255, 255));
        pr1.setText("Update Status");

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 102, 0));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/co.png"))); // NOI18N
        jButton10.setText("Delete Order");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecs/mainlogo.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destination)
                    .addComponent(weight)
                    .addComponent(servicetype)
                    .addComponent(dimensions)
                    .addComponent(type)
                    .addComponent(origin)
                    .addComponent(jLabel8)
                    .addComponent(as)
                    .addComponent(receiveradress4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getid, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setid, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimension1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origin1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicetype1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aa)
                    .addComponent(sendername1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveradress2)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveradress)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receivername1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveradress3)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pr)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 87, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(receiveradress5)
                        .addGap(221, 221, 221))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(pr1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(receiveradress5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pr1))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiveradress4)
                    .addComponent(getid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(pr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(setid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(origin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(destination1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destination))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(type1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dimensions, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dimension1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(weight)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(weight1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(servicetype)
                                    .addComponent(servicetype1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(as)
                                    .addComponent(amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(aa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendername1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(receiveradress2)
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveradress3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receivername1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receiveradress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setidActionPerformed

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount1ActionPerformed

    private void getidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getidActionPerformed
    String id;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/CECS","root","password");
            String sql1="SELECT * FROM ORDERDETAILS WHERE id=?";
            java.sql.PreparedStatement Psmt1=Con.prepareStatement(sql1);
            String i= getid.getText();
            Psmt1.setString(1,i);
            java.sql.ResultSet rs=Psmt1.executeQuery();
            while(rs.next())
            {
                id=rs.getString("id");
                System.out.println("id"+id);
                setid.setText(id);
                String org=rs.getString("origin");
                origin1.setText(org);
                String des=rs.getString("destination");
                destination1.setText(des);
                String ty=rs.getString("type");
                type1.setText(ty);
                String wt=rs.getString("weight");
                weight1.setText(wt);
                String dn=rs.getString("dimension");
                dimension1.setText(dn);
                String st=rs.getString("servicetype");
                servicetype1.setText(st);
                String sn=rs.getString("sendername");
                sendername1.setText(sn);
                String rn=rs.getString("receivername");
                receivername1.setText(rn);
                String sa=rs.getString("senderadress");
                senderadress1.setText(sa);
                String ra=rs.getString("receiveradress");
                receiveradress1.setText(ra);
                String amn=rs.getString("amount");
                amount1.setText(amn);
                String prg=rs.getString("progress");
                progress.setSelectedItem(prg);
            
            }
            if(setid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Order ID");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Details Displayed Plesase Check");
                
            }
                
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new EmployeePage(nm1,id1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         try{
            java.sql.Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/CECS","root","password");
            String sql="UPDATE ORDERDETAILS SET progress=?,emp_id=? WHERE id=?";
            java.sql.PreparedStatement Psmt=Con.prepareStatement(sql);
            Psmt.setString(3,id);
            Psmt.setString(2, id1);
            System.out.println("id"+id1);
            String pg=progress.getSelectedItem().toString();
            if(pg=="20 (Order Placed)")
            {
                Psmt.setString(1,"20");
            }
            else if(pg=="40 (Order Shipped)")
            {
                Psmt.setString(1,"40");
            }
            else if(pg=="60 (In Shipping)")
            {
                Psmt.setString(1,"60");
            }
            else if(pg=="80 (Arrived at final destination)")
            {
                Psmt.setString(1,"80");
            }
            else if(pg=="100 (Order Delivered)")
            {
                Psmt.setString(1,"100");
            }
             if(setid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Order ID");
            }
             else
             {
            Psmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Status Updated");
            setid.setText("");
            getid.setText("");
            origin1.setText("");
            destination1.setText("");
            type1.setText("");
            weight1.setText("");
            dimension1.setText("");
            servicetype1.setText("");
            sendername1.setText("");
            senderadress1.setText("");
            receivername1.setText("");
            receiveradress1.setText("");
            amount1.setText("");
             }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //delete
        try{
             java.sql.Connection Con=DriverManager.getConnection("jdbc:derby://localhost:1527/CECS","root","password");
            String sql="DELETE FROM ORDERDETAILS WHERE id=?";
            java.sql.PreparedStatement Psmt=Con.prepareStatement(sql);
            Psmt.setString(1,id);
             if(setid.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Please Enter Correct Order ID");
            }
             else
             {
             Psmt.executeUpdate();
             JOptionPane.showMessageDialog(null,"Order Deleted");
             setid.setText("");
            getid.setText("");
            origin1.setText("");
            destination1.setText("");
            type1.setText("");
            weight1.setText("");
            dimension1.setText("");
            servicetype1.setText("");
            sendername1.setText("");
            senderadress1.setText("");
            receivername1.setText("");
            receiveradress1.setText("");
            amount1.setText("");
             }
            
        }
        catch(Exception e)
           {
                JOptionPane.showMessageDialog(null, e);     
            }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JTextField amount1;
    private javax.swing.JLabel as;
    private javax.swing.JLabel destination;
    private javax.swing.JTextField destination1;
    private javax.swing.JTextField dimension1;
    private javax.swing.JLabel dimensions;
    private javax.swing.JTextField getid;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel origin;
    private javax.swing.JTextField origin1;
    private javax.swing.JLabel pr;
    private javax.swing.JLabel pr1;
    private javax.swing.JComboBox<String> progress;
    private javax.swing.JLabel receiveradress;
    private javax.swing.JTextArea receiveradress1;
    private javax.swing.JLabel receiveradress2;
    private javax.swing.JLabel receiveradress3;
    private javax.swing.JLabel receiveradress4;
    private javax.swing.JLabel receiveradress5;
    private javax.swing.JTextField receivername1;
    private javax.swing.JTextArea senderadress1;
    private javax.swing.JTextField sendername1;
    private javax.swing.JLabel servicetype;
    private javax.swing.JTextField servicetype1;
    private javax.swing.JTextField setid;
    private javax.swing.JLabel type;
    private javax.swing.JTextField type1;
    private javax.swing.JLabel weight;
    private javax.swing.JTextField weight1;
    // End of variables declaration//GEN-END:variables
}
